apiVersion: apps/v1
kind: Deployment
metadata:
  name: uidgen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uidgen
  template:
    metadata:
      labels:
        app: uidgen
    spec:
      containers:
        - name: uidgen-container
          image: uid_gen:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: uidservice
spec:
  selector:
    app: uidgen
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: LoadBalancer
